### ISSUE TITLE
HotReload connection issues using physical device (iPad)

### ISSUE THREAD

**Issue by SamGustinHdr** [JaneySprings/DotNet.Meteor#102]
Any ideas on how I can troubleshoot this error that keeps showing up in my debug console when saving XAML? I haven't been able to get hot reload working with my iPad.

[HotReload]: Connection to server is not established
warning HE0053: Failed to create a USB tunnel between the ports 9988 (on device) and 9988 (on the mac): USB connect timeout (61), likely because the app failed to launch. Please review device logs and/or crash reports for more information.

I have tried a few different ports in the extension settings and that didn't help the situation. I also didn't find anything else helpful in the logs, unless I was looking in the wrong spot.

Thanks in advance!

**Comment by JaneySprings** [comment]
Hi @SamGustinHdr ! Can you try to specify your __changed__ port number in the builder extension?
<img width="604" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/bb843ce5-586a-4443-8671-ca768a96eea9">

**Comment by SamGustinHdr** [comment]
Never mind, this was an issue on my end. Sorry to bother you!
