### ISSUE TITLE
MAUI Profiler - dsrouter connection not getting established (macOS)

### ISSUE THREAD

**Issue by kavitap081** [JaneySprings/DotNet.Meteor#103]
Hi,
I am running MAUI profiler using  trace profileMode. I am able to launch the application on my device but then  dsrouter is not able to create the connection between profiler and device. I am seeing "Router stopped" in my DEBUG CONSOLE window. 
From your troubleshooting documentation [here](https://github.com/JaneySprings/DotNet.Meteor?tab=readme-ov-file#troubleshooting), i tried updating port in .NET Meteor settings, but no use.

Here's my launch.json file 
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/147433670/c98e72a0-a659-4fc1-af43-b271538ffde3)

Here's the screenshot of debug console messages :
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/147433670/68f9ec76-f5c3-4b42-be81-c54e0a9512bb)

Can you please help to identify the issue and to move forward with profiling.

**Comment by JaneySprings** [comment]
Hi @kavitap081 ! Can you try to delete the `bin`, `obj` folders from your project?

**Comment by kavitap081** [comment]
Hey @JaneySprings , I tried that, but still getting the same error. Could it be the issue as its running on macOS ? Also, i reset the port to 9000 again.

**Comment by JaneySprings** [comment]
`Shutting down due to error: ` **Address already in use**
It seems very strange. Are you sure changing your address doesn't help you? Maybe 11000
<img width="291" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/18f51ef6-d544-43d5-9004-422e2ebbd7b6">

**Comment by kavitap081** [comment]
@JaneySprings If i change the port to say 11000. I am getting another error in Debug console. This is the error :

![image](https://github.com/JaneySprings/DotNet.Meteor/assets/147433670/e3e26150-c8f4-4537-91c3-f66d92298b1a)

**Comment by kavitap081** [comment]
@JaneySprings   Sure. Here's the environemnt info 
dotnet --version is 8.0.301
and here's the dotnet workload list :
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
wasi-experimental          8.0.6/8.0.100         SDK 8.0.300        
maui                       8.0.40/8.0.100        SDK 8.0.300  

![image](https://github.com/JaneySprings/DotNet.Meteor/assets/147433670/0cbb3b5e-ee85-4585-a49c-aa8dd02f7c9d)

I am using Android device Samsung A53.

**Comment by kavitap081** [comment]
Hi @JaneySprings  !
Any update on it? Were you able to reproduce the issue ?

**Comment by JaneySprings** [comment]
Hi @kavitap081 ! Can you test it on the following versions? 
I built it for Mac (Apple + Intel versions)

[DotNet.Meteor.v5.0.0_darwin-arm64.vsix.zip](https://github.com/user-attachments/files/15836307/DotNet.Meteor.v5.0.0_darwin-arm64.vsix.zip)
[DotNet.Meteor.v5.0.0_darwin-x64.vsix.zip](https://github.com/user-attachments/files/15836311/DotNet.Meteor.v5.0.0_darwin-x64.vsix.zip)

Just open VSCode, open the `extensions` tab and click `install from vsix`
<img width="593" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/dcd0acc0-41fa-49b5-b7d6-4539d09123f1">

**Just make sure that you don't have any `dotnet-dstouter` processes running**

**Comment by kavitap081** [comment]
hey @JaneySprings ,
It worked with the vsix file you shared. Thanks , i am able to create .gcdump and .speedscope.json files.

**Comment by JaneySprings** [comment]
Yep, this error displays after the connection timeout. I changed the order of events (Microsoft documentation about profiling is incorrect).

I will create a fix for `4.7.0` and higher versions as soon as possible!

**Comment by kavitap081** [comment]
Thanks a lot @JaneySprings for quick fix,
Another thing which is not related to this extension, but  can you let me know if there's a way to open .gcdump file in mac. I only see it can open in WindowsPerf and Visual studio ( of windows). I need that to memory leaks data of my app. 

Marking this issue as closed.

**Comment by JaneySprings** [comment]
Yes, check this open-source dotnet tool
https://github.com/1hub/dotnet-heapview
