### ISSUE TITLE
the ext take so much memory

### ISSUE THREAD

**Issue by wxyer** [JaneySprings/DotNet.Meteor#105]
the ext take so much memory,amost 50 percent

**Comment by JaneySprings** [comment]
Hi! Can you send your memory usage?
This is the memory consumption on my machine: ~350mb

<img width="952" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/2c2fc90f-60b1-479e-8c4f-97ca2e0363c2">
