### ISSUE TITLE
Provide a way to set iOS Simulator to X64 using Visual Studio Code

### ISSUE THREAD

**Issue by shobanasuresh** [JaneySprings/DotNet.Meteor#108]
We use Microsoft AppCenter Nuget packages in our .Net MAUI application for iOS. AppCenter packages are compiled only for ios-arm64 and iossimulator-x64 targets.

When using Apple M1/M2 host machines with .NET 8 to debug from Visual Studio Code, .NET Meteor defaults to using an arm64 simulator causing appcenter functionalities unusable.

Can you please provide a way to use iossimulator-x64 runtime when using .Net meteor vscode extension?

Reference: https://github.com/dotnet/maui/discussions/20349#discussioncomment-8363738

**Comment by JaneySprings** [comment]
Hi @shobanasuresh ! Yes, you can use the following workaround:
https://github.com/JaneySprings/DotNet.Meteor/pull/53#issuecomment-1511875479

But I highly recommend requesting the `iossimulator-arm64` support!

**Comment by shobanasuresh** [comment]
Hi @JaneySprings, Thanks for sharing the workaround. 

>But I highly recommend requesting the iossimulator-arm64 support!
Based on https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755#issuecomment-2022181519, arm64 support will not be added as the package will be retired next year.
