### ISSUE TITLE
Android devices not showing on the device selector

### ISSUE THREAD

**Issue by fourad** [JaneySprings/DotNet.Meteor#109]
on macos some devices i plug get displayed on some not, adb is showing the device plugged but in the select device menu i dont show.

**Comment by JaneySprings** [comment]
Hi, @fourad ! Can you send the `adb devices -l` command output, please?
For example:
```
> adb devices -l
List of devices attached
GESDQ23211100349       device usb:2017152X product:DBY2-W91 model:DBY2_W91 device:HWDBY2 transport_id:1

```
