### ISSUE TITLE
Not seeing "trace complete" after using trace profiling 

### ISSUE THREAD

**Issue by GBarbieri-IPS** [JaneySprings/DotNet.Meteor#112]
After setting up the launch.json to prfile as 'trace' it seems that I'm never getting the following

Trace completed.
Writing:	/Users/You/.../MauiProf/.meteor/MauiProf.speedscope.json
Conversion complete

Currently what I see in my debug logs.

Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]
WARNING: dotnet-dsrouter is a development tool not intended for production environments.

info: dotnet-dsrouter-5872[0]
Starting dotnet-dsrouter using pid=5872
Serving...
info: dotnet-dsrouter-5872[0]
Starting IPC server (dotnet-diagnostic-dsrouter-5872) <--> TCP server (127.0.0.1:9001) router.
All files should be loaded. Notifying the device.
Performing Incremental Install
Success
Install command complete in 1412 ms
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=embc.zack/crc64ce0a2486487a3447.MainActivity }

Currently debugging on Android device. Only seeing the .nettrace file being generated.

**Comment by JaneySprings** [comment]
Hi @GBarbieri-IPS ! Yes, I can reproduce it. I think something broken in the new dotnet or workload version. I will research it.

**Comment by GBarbieri-IPS** [comment]
Awesome thanks so much!

**Comment by JaneySprings** [comment]
Fixed in `5.2.4`. Check for updated in VSCode!

**Comment by GBarbieri-IPS** [comment]
Your Amazing, pulling now! Thanks so much!
