### ISSUE TITLE
Not able to /dump and no traces are collected.

### ISSUE THREAD

**Issue by haavamoa** [JaneySprings/DotNet.Meteor#115]
Hi, this is an awesome project. I just tried it to memory profile my iOS app, but when I do a dump I get the following:

```csharp
/dump -v
command handled by DotNet.Meteor.Debug.GCDumpLaunchAgent
Writing gcdump to '/Users/<myuser>/code/<myproject>/src/<myproject>/.meteor/<myproject>.gcdump'...
0,0s: Creating type table flushing task
0,0s: [Error] Exception during gcdump: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.Stream.ReadAtLeastCore(Span`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream)
at System.IO.BinaryReader.InternalRead(Int32 numBytes)
at System.IO.BinaryReader.ReadUInt16()
at Microsoft.Diagnostics.NETCore.Client.IpcHeader.Parse(BinaryReader reader) in /Users/runner/work/1/s/src/DotNet.Diagnostics/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcHeader.cs:line 55
at Microsoft.Diagnostics.NETCore.Client.IpcMessage.Parse(Stream stream) in /Users/runner/work/1/s/src/DotNet.Diagnostics/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcMessage.cs:line 117

```

> Note; `<myproject>` is just me obfuscating.

I do get a connected successfully of dotnet-dsrouter:
```
info: dotnet-dsrouter-17120[0]
Starting dotnet-dsrouter using pid=17120
info: dotnet-dsrouter-17120[0]
Starting IPC server (/Users/<myuser>/ios-port.lock) <--> TCP client (127.0.0.1:11000) router.
info: dotnet-dsrouter-17120[0]
Successfully connected new device, id=3.
```
I've also tried the trace profiling, but no luck there as well :( 

I've tried the [troubleshooting](https://github.com/JaneySprings/DotNet.Meteor?tab=readme-ov-file#troubleshooting), but no luck :(

Android works fine, but not iOS :(

**Comment by haavamoa** [comment]
➤ dotnet workload list                        

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
ios                        17.5.8020/8.0.100      SDK 8.0.300        
maui                       8.0.72/8.0.100         SDK 8.0.300        
android                    34.0.113/8.0.100       SDK 8.0.300

**Comment by JaneySprings** [comment]
Hi, @haavamoa !
> I've also tried the trace profiling, but no luck there as well :(

Let's try to find the problem using the `trace` mode:

- Run your iOS application with trace. Can you see the following messages?
<img width="936" alt="image" src="https://github.com/user-attachments/assets/008ab449-c8c6-4a0f-9f8b-6f7efddbacda">

- Can you see the `Output File: ` message?
- If you **don't see** this message, is your app currently showing your MainPage or .NET SplashScreen?

**Comment by haavamoa** [comment]
> Hi, @haavamoa !
> 
> > I've also tried the trace profiling, but no luck there as well :(
> 
> Let's try to find the problem using the `trace` mode:
> 
> * Run your iOS application (you can use debug + simulator) with trace. Can you see the following messages?
> 
> <img alt="image" width="936" src="https://private-user-images.githubusercontent.com/48021947/358672489-008ab449-c8c6-4a0f-9f8b-6f7efddbacda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzY1NDUsIm5iZiI6MTcyMzgzNjI0NSwicGF0aCI6Ii80ODAyMTk0Ny8zNTg2NzI0ODktMDA4YWI0NDktYzhjNi00YTBmLTlmOGItNmY3ZWZkZGJhY2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE5MjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMTk4ZDY1N2U4MjBkMWYzN2UzNWM1YTQzNGJjMGUxOGMwYjk0NzA0YTNlNGVjZTA5MjljYzJkMDdhZWI2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pyMmzmGD-83mkzFanhSidxodEFOM3r7Jl9JscqR5uA8">
> * Can you see the `Output File: ` message?
> * If you **don't see** this message, is your app currently showing your MainPage or it is .NET SplashScreen?

Unfortunately , `trace` seems to exit my application once the splash screen is gone.

**Comment by JaneySprings** [comment]
Can you check this behavior with simulator?

**Comment by haavamoa** [comment]
I just did, now I get a infamous [clang+++ error with AppCenter package](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755) when building. 
```
usr/local/share/dotnet/x64/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(1641,3): error : clang++ exited with code 1: [<my-repo-patch>/<my-csproj>csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/x64/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(1641,3): error : ld: in <my-repo-patch>/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenter.a(MSACAppCenter.o), building for iOS Simulator, but linking in object file built for iOS, file '<my-repo-path>/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenter.a' [<my-repo-path>/<my-csproj>csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/x64/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(1641,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [<my-repo-path>/<my-csproj>csproj::TargetFramework=net8.0-ios]
```

This is fixed by adding this to the csproj, which makes sure I can build in Rider, but somehow not when I am using .NET Meteor in VSCode :(

```
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
        <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier> 
    </PropertyGroup>
```

**Comment by haavamoa** [comment]
Ah yeah, I notice that in VSCode it sets `-p:RuntimeIdentifier=iossimulator-arm64` when building, and my property will get overridden. 

I forgot to mention I run on Apple Sillicon.

**Comment by JaneySprings** [comment]
Yes, you can override it. Update to the latest version (`5.3.1` and higher) and use the following workaround:

- Create `.vscode/tasks.json` file
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "dotnet-meteor.task",
			"target": "build",
			"problemMatcher": [
				"$dotnet-meteor.problemMatcher"
			],
			"label": "dotnet-meteor: Build",
			"args": [
                               // It removes auto provided value
				"-p:RuntimeIdentifier="
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

And update your `launch.json` file
```json
{
    "version": "0.2.0",
    "configurations": [
        {
        ...
        },
        // Your new configuration for simulator-x64 only
        {
            "name": "(simX64) .NET Meteor Debugger",
            "type": "dotnet-meteor.debugger",
            "request": "launch",
            // You can specify path to the application here
            "program": "${workspaceFolder}/bin/Debug/net8.0-ios/iossimulator-x64/MauiTestApp.app",
            "preLaunchTask": "dotnet-meteor: Build",
        }
    ]
}
```

And you can select your new configuration here:
<img width="537" alt="image" src="https://github.com/user-attachments/assets/ce516d5f-7979-4d14-8583-92f577acda14">

**Comment by haavamoa** [comment]
Thanks, now It builds but it's unable to launch due to looking in the wrong folders:

```
Failed to launch the simulator: Could not find file '<my-repo-path>/bin/Debug/net8.0-ios/iossimulator-arm64/<myapp>.
```

We can continue trying to solve this, or can we focus on device? Testing simulator is nice, but device is what I will have to run on when collecting memory dumps in the end of the day.

**Comment by JaneySprings** [comment]
Also you can try to reproduce it in the new empty project (dotnet new maui). Maybe some library is reason of this behavior.
I can't reproduce this on a simulator or device with the latest version of iOS.

**Comment by haavamoa** [comment]
Just tested with this project: https://github.com/DIPSAS/DIPS.Mobile.UI , and it works.

**Comment by haavamoa** [comment]
Its nice, but at the same time not as the actual app I want to profile does not work :(  

Originally, I  wanted to test gcdump on my project. As you see it runs, but it throws exceptions when I dump. Is there anything I can do to get some more details regarding that exception?

```
/dump -v
command handled by DotNet.Meteor.Debug.GCDumpLaunchAgent
Writing gcdump to '/Users/<myuser>/code/<myproject>/src/<myproject>/.meteor/<myproject>.gcdump'...
0,0s: Creating type table flushing task
0,0s: [Error] Exception during gcdump: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.Stream.ReadAtLeastCore(Span`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream)
at System.IO.BinaryReader.InternalRead(Int32 numBytes)
at System.IO.BinaryReader.ReadUInt16()
at Microsoft.Diagnostics.NETCore.Client.IpcHeader.Parse(BinaryReader reader) in /Users/runner/work/1/s/src/DotNet.Diagnostics/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcHeader.cs:line 55
at Microsoft.Diagnostics.NETCore.Client.IpcMessage.Parse(Stream stream) in /Users/runner/work/1/s/src/DotNet.Diagnostics/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcMessage.cs:line 117
```
