### ISSUE TITLE
 Error launch.json - does not deploy to simulator with version 5.3.1

### ISSUE THREAD

**Issue by marcoseraphin** [JaneySprings/DotNet.Meteor#117]
Hi Nikita,

as you know I am a frequent user of your great .Net Meteor extension for VS for Mac managing my .NET MAUI Apps.

Yesterday I updated to the latest version 5.3.1

In my launch.json for a specific project I have this entry:

 "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Meteor: iOSSimulator-x64",
            "type": "dotnet-meteor.debugger",
            "request": "launch",
            "runtime": "iossimulator-x64",
            "preLaunchTask": "Build iOSSimulator-x64"
        },

I need his iossimulator-x64 flag because currently my customer still uses MS AppCenter packages, this will change in the future (perhaps Sentry) but currently it is working with this flag.

BUT after updating to version 5.3.1 the app does not even be deployed to the iOS Simulator. In my VS Code debug window I saw this message:

Failed to launch the simulator: Could not find file '/Users/marcoseraphin/Documents/ProjectName.App/bin/Debug/net8.0-ios/iossimulator-arm64/ProjectName.App.app/ProjectName.App‘.

After trying other launch.json options I did NOT get it to work and downgraded your extension back to 5.3.0…and everything works as expected.

Any hint or how do I correctly change my launch.json file to get it deployed and running with the current version 5.3.1 ?

Best

Marco

**Comment by JaneySprings** [comment]
Hi @marcoseraphin ! Use this new workaround: https://github.com/JaneySprings/DotNet.Meteor/issues/116#issuecomment-2296154879

I will create a documentation about this bug.

**Comment by marcoseraphin** [comment]
Yes, it works, I have modified the launch.json using the "device" tag and now I could deploy and start my app using the current v5.3.1 version.

Thanx

Marco

**Comment by JaneySprings** [comment]
Yeah, sorry for that, `runtimeId` property - is temporary hack. This new solution will be much better and may be useful in other cases =)
