### ISSUE TITLE
Cannot run on clear VSC

### ISSUE THREAD

**Issue by michalpobuta** [JaneySprings/DotNet.Meteor#120]
Hi, I tried to install and launch .net meteor on my project, but when I click start nothing happened. "Start debugging" and "Start without debugging" also don't respond. Nothing in logs, not a single error.

MacOs

**Comment by JaneySprings** [comment]
Hi! Can you send the `/Users/NAME/.vscode/extensions/nromanov.dotnet-meteor-X.X.X/extension/bin/Debug/logs/Debug.log` file, please?

**Comment by michalpobuta** [comment]
@JaneySprings no such file or directory: logs

**Comment by michalpobuta** [comment]
@JaneySprings It is works on empyt project, but idk what is wrong with mine

**Comment by JaneySprings** [comment]
Can you send an example? I think that you can copy only `csproj` file because the problems are usually there.

**Comment by michalpobuta** [comment]
@JaneySprings I found it. I had some config in .target files and vsc didn't find them, so I had to put them explicit in csproj

**Comment by JaneySprings** [comment]
Everything is OK for now?
If you can debug this project from VisualStudio for Windows, please, you can send me an example where I can fix this issue.

**Comment by michalpobuta** [comment]
@JaneySprings now I get incorrect path to program, but it is good path. I am using rider actually, so maybe this is the problem

**Comment by JaneySprings** [comment]
OK, close for now.
