### ISSUE TITLE
Incorrect Path To Program

### ISSUE THREAD

**Issue by ajbates2** [JaneySprings/DotNet.Meteor#121]
Not sure how to solve this. I tried adding the program prop to the launch.json and I get the same issue, and when I click the debug log I get nothing.

Running on this on windows to an android emulator if that helps

![Screenshot 2024-09-24 181354](https://github.com/user-attachments/assets/9915c7fd-8c62-4aab-9698-240186e33273)

**Comment by JaneySprings** [comment]
Hi @ajbates2 ! Can you check this directory? Do you see any `*-Signed.apk` file?

**Comment by ajbates2** [comment]
Yes that is what it is defaulting to

**Comment by JaneySprings** [comment]
This file path is equals to the file path in the error?

**Comment by ajbates2** [comment]
Yes it defaults to this path `${workspaceFolder}\\bin\\Debug\\net8.0-android\\com.${appName}.mobile.apk`

**Comment by JaneySprings** [comment]
If this file exists, the application should start. Can you send any example app?

I can't reproduce it on my pc:
![image](https://github.com/user-attachments/assets/146cac90-4893-4f3a-b5cc-29caf8ad4873)

**Comment by rmorin04** [comment]
same issue on my end

**Comment by ajbates2** [comment]
So, I am able to get meteor working on a fresh maui build but I'm running into these issues when trying to get an existing solution running. Do you know of any nuget package conflicts that exist?

**Comment by JaneySprings** [comment]
Check the following code:
https://github.com/JaneySprings/DotNet.Meteor/blob/23edb76c0e3fe12ad334205b94c921574094d334/src/DotNet.Meteor.Debug/LaunchConfiguration.cs#L40-L42

Check again the path to the application that the error gives you. I am sure there is a mistake in it.

Also you can check the `Platforms\Android\AndroidManifest.xml` file. Maybe you have something like `package="com.mycompany.myapp"` (Not the same as `ApplicationId` in csproj) ?
