### ISSUE TITLE
Unable to start profiling on iOS device

### ISSUE THREAD

**Issue by steffos** [JaneySprings/DotNet.Meteor#123]
Thank's for a great extension :) 

I'm unable to profile my app on iOS device. I have followed the 'Profile the Application' instructions from the README and it works great for Android devices. But when I choose an iOS device as Debug Target and choose 'Run without debugging' I still can see it tries to start profiling with Android options '
`Executing task: dotnet build <MyAppProject.Maui.csproj> -p:Configuration=Debug -p:TargetFramework=net8.0-android -p:AndroidSdkDirectory=<My Android SDK directory> -p:EmbedAssembliesIntoApk=true -p:AndroidEnableProfiler=true`

How can I start an iOS profiling session?

**Comment by carlssonstefan** [comment]
It seems it was me who missed the instructions line: 'In the status bar, select a project (if your opened folder contains several projects) and a configuration (the debug is the default). Click the device name and select a target device/emulator from the opened panel.'. 

So all sorted out, will close this issue.

**Comment by steffos** [comment]
It seems it was me who missed the instructions line: 'In the status bar, select a project (if your opened folder contains several projects) and a configuration (the debug is the default). Click the device name and select a target device/emulator from the opened panel.'.

So all sorted out, will close this issue.
