### ISSUE TITLE
Documentation on how to set target framework for debugger

### ISSUE THREAD

**Issue by acehoss** [JaneySprings/DotNet.Meteor#124]
I am running on macOS (arm64), and when I launch the application from the debugger it always launches the android version. I want to launch the maccatalyst version.

I see in the documentation how I can customize the build task, and I could add the `-p:TargetFramework=net8.0-maccatalyst` parameter there. I see in the output window that this is passed to the build task, though there are still android args present as well:
```
Executing task: dotnet build /Users/aaron/Projects/CheatCode/CheatClient/CheatClient.csproj -p:Configuration=Debug -p:AndroidSdkDirectory=/Users/aaron/Library/Android/Sdk -p:EmbedAssembliesIntoApk=true -p:TargetFramework=net8.0-maccatalyst 
```

The build succeeds, but then the debugger still launches the android emulator and runs the android app.

I've seen an issue or two using the `device` property in the configuration to override some things to launch the iOS simulator, but I couldn't make that work for launching the macOS app.

Thanks in advance!

**Comment by JaneySprings** [comment]
Hi @acehoss ! Do you see the device status bar item?

You need to select a device that you want to target:
<img width="862" alt="Screenshot 2024-10-01 at 17 20 31" src="https://github.com/user-attachments/assets/b65e8ff6-897e-4a2f-8fc2-87ce37838b64">

**Comment by acehoss** [comment]
🤦🏼‍♂️ I knew it had to be easier than I was making it. Yep, it's right there and works great! Thanks so much!

**Comment by JaneySprings** [comment]
No problem! Feel free to ask anything!
