### ISSUE TITLE
Custom project configuration

### ISSUE THREAD

**Issue by kireCC** [JaneySprings/DotNet.Meteor#125]
I am having issues getting the extension to recognize my custom project configurations. This used to be an issue on c# dev kit as well, but it seems to be resolved as of recent.

From my csproj:

<img width="808" alt="image" src="https://github.com/user-attachments/assets/b27f99cd-683f-4c3b-8bb0-72a53fa0999a">

Meteor only offers the defaults:

<img width="684" alt="image" src="https://github.com/user-attachments/assets/c49e469b-cc51-4c8a-bafa-8b2a750d5872">

I tried specifying my custom config in the launch script, but that only changes the path after the app has been built and Meteor is searching for the bundle to install. In the actual .net build script project configuration is still set to just Debug or Release.

**Comment by JaneySprings** [comment]
Hi, @kireCC ! You can specify custom configuration in the `launch.json`:
![image](https://github.com/user-attachments/assets/baa42afe-795d-4ef4-ad04-ba5576af2bca)

**Comment by kireCC** [comment]
Hi @JaneySprings, thank you for the quick reply!

Specifying the configuration using the "configuration" property in the launch.json file still passed just Debug or Release in the "dotnet build" command. But I managed to pass my custom config successfully by modifying the Build task in tasks.json like you suggested.

Many thanks!

**Comment by JaneySprings** [comment]
Yeah, I will try to add all configurations to the `"debug"` statusbar item menu.
