### ISSUE TITLE
Android .NET MAUI app fully reinstalls on each build and deploy

### ISSUE THREAD

**Issue by domneedham** [JaneySprings/DotNet.Meteor#128]
When debugging via .NET Meteor for our .NET MAUI Android app, the app is fully reinstalled, losing preferences, permissions etc. This requires going through app setup, such as logging in, again every time we want to debug. 

Environment:

macOS: Our dev team see it on Ventura and Sequoia 
.NET MAUI: 8.0.40 but any above. Not sure about .NET 9 and MAUI rc

**Comment by JaneySprings** [comment]
Hi, @domneedham ! Uncheck the following setting:
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/21bd7d60-76a6-436f-85ea-3cdbc26051e8">

**Comment by domneedham** [comment]
Thanks for replying so fast, that does fix it. 

Do you know why this only affects Android? iOS, Mac and Windows with the same setting on does not lose any previous install data?

**Comment by JaneySprings** [comment]
No problem!
Because Windows, MacOS and iOS are store they cache in the different locations (Like `ApplicationSupport` or `%AppData%`) and I don't clean it.
But Android has some installation issues if you don't uninstall this application before the installation (version downgrade etc.)

**Comment by domneedham** [comment]
Makes sense. Thanks again!
