### ISSUE TITLE
No android physical device in select device menu.

### ISSUE THREAD

**Issue by OudomMunint** [JaneySprings/DotNet.Meteor#130]
On macOS, in the select device menu android physical device doesn't show up. Only Mac, iOS simulators and iOS physical device. Android Device is connected via USB and has USB debugging enabled.

![image](https://github.com/user-attachments/assets/eb59d181-8239-4c68-ac31-ce91f501421d)

.Net Meteor v5.6.2

**Comment by JaneySprings** [comment]
Hi, @OudomMunint !

What kind of Android SDK installation are you using? With AndroidStudio or with VS for Mac?

Also you can check the logs in the following folder:
‘’’
~/.vscode/extensions/nromanov.dotnet-meteor.5.6.2/extension/bin/Workspace/Logs
‘’’

**Comment by OudomMunint** [comment]
> Hi, @OudomMunint !
> 
> What kind of Android SDK installation are you using? With AndroidStudio or with VS for Mac?
> 
> Also you can check the logs in the following folder:
> 
> ```
> ~/.vscode/extensions/nromanov.dotnet-meteor.5.6.2/extension/bin/Workspace/Logs
> ```

I think Android SDK is set via VS for Mac as I don't have Android Studio installed

Logs suggests something off with ADB.

_**Debug.log:**_
```
16:10:16.3657|Fetching devices...
16:10:16.3698|System.IO.FileNotFoundException: Could not find adb tool
16:10:16.3820|MacOS devices added.
16:10:16.5286|Apple physical devices added.
16:10:16.5366|Apple virtual devices added.
16:10:16.5366|Devices fetched. Total: 25.
```

_**Error.log:**_
```
2024-10-21 16:10:16.3698|System.IO.FileNotFoundException: Could not find adb tool
at DeviceProvider.GetDevices at Program.AllDevices at Program.Main
/Users/runner/work/1/s/src/DotNet.Meteor.Workspace/DeviceProvider.cs[22]
```

**Comment by OudomMunint** [comment]
@JaneySprings I've just installed android studio and don't the set up. It seems that was the missing link. I'm able to see both android physical device and emulators now. Closing this issue. Thanks! 🙏
