### ISSUE TITLE
Does not profile iOS app in release configuration ("profilerMode": "trace")

### ISSUE THREAD

**Issue by nikamvd** [JaneySprings/DotNet.Meteor#132]
Does not profile iOS app in release configuration ("profilerMode": "trace"); but works for iOS (Debug). Also works for Android Release / Debug both configurations.

Shows below output in debug console on vs code -
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/bin/mlaunch
WARNING: dotnet-dsrouter is a development tool not intended for production environments.

info: dotnet-dsrouter-14198[0]
Starting dotnet-dsrouter using pid=14198
info: dotnet-dsrouter-14198[0]
Starting IPC server (/Users/_username_/ios-port.lock) <--> TCP client (127.0.0.1:9000) router.
info: dotnet-dsrouter-14198[0]
Successfully connected new device, id=2.

But does not create speedscope file at end of session

using below launch configuration -
{
            "name": ".NET Meteor Profiler",
            "type": "dotnet-meteor.debugger",
            "request": "launch",
            "profilerMode": "trace",
            "preLaunchTask": "dotnet-meteor: Build"
        }

Softwares -
VS Code - Version: 1.94.2 (Universal)
.NET Meteor - v5.7.0
Xcode - Version 16.0 (16A242d)
dotnet workload list
maui                       8.0.82/8.0.100        SDK 8.0.400

**Comment by JaneySprings** [comment]
Hi, @nikamvd ! It is iOS device or simulator?

**Comment by nikamvd** [comment]
> Hi, @nikamvd ! It is iOS device or simulator?

Its physical device: iPhone 12; iOS 16.3

**Comment by JaneySprings** [comment]
https://github.com/xamarin/xamarin-macios/issues/21530

**Comment by JaneySprings** [comment]
Fixed in `5.8.2`
