### ISSUE TITLE
Doesn't start on iPhone physical device

### ISSUE THREAD

**Issue by tpitman** [JaneySprings/DotNet.Meteor#134]
I looked everywhere I could think of and can't figure out how to target my iPhone physical device.

When I have both an iPhone and Android phone connected, it will run on the Android phone. If I disconnect the Android phone and try again it says it can't find the Android phone.

In the debug target I have my iPhone selected. If I do a normal debug session with that target, it debugs fine on the iPhone.

When I try to do the trace it seems to be stuck trying to go to the Android phone.

How do I tell it to do the trace on the iPhone?

**Comment by JaneySprings** [comment]
Hi, @tpitman !
Can you send something like screen recording?

.NET Meteor can't change your device If you select `iOS Device` here
<img width="1170" alt="Screenshot 2024-10-29 at 11 01 41" src="https://github.com/user-attachments/assets/a750a51e-6649-4bf2-8dfd-809d48f90a49">

**Comment by tpitman** [comment]
I notice that just recentl. I am sure that will fix it. I have always been using the Debug Target because that was the only place I really saw a device name before. I wasn't sure what that one you called out was.

Thanks for the quick reponse.
