### ISSUE TITLE
dotnet-meteor client: couldn't create connection to server.

### ISSUE THREAD

**Issue by AramMar** [JaneySprings/DotNet.Meteor#135]
Hello,

I am getting the same error and i could not find anything about the issue.

![image](https://github.com/user-attachments/assets/ac9537a9-6a3c-46a8-a86a-1da09828a89e)

in output

[Error - 5:54:54 PM] dotnet-meteor client: couldn't create connection to server.
Error: spawn EPERM
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:796:9)
	at c:\Users\.....\.vscode\extensions\nromanov.dotnet-meteor-5.9.1-win32-x64\extension\extension.js:1:298419
	at async S.createConnection (c:\Users\....\.vscode\extensions\nromanov.dotnet-meteor-5.9.1-win32-x64\extension\extension.js:1:134949)
	at async S.start (c:\Users\amargaryan\.vscode\extensions\nromanov.dotnet-meteor-5.9.1-win32-x64\extension\extension.js:1:125464)

launch.json

 "configurations": [
        {
            "name": ".NET Meteor Debugger",
            "type": "dotnet-meteor.debugger",
            "request": "launch",
            "preLaunchTask": "dotnet-meteor: Build"
        },
        {
            "name": ".NET Meteor Profiler",
            "type": "dotnet-meteor.debugger",
            "request": "launch",
            "profilerMode": "gcdump",
            "preLaunchTask": "dotnet-meteor: Build"
        }
    ]

**Comment by JaneySprings** [comment]
Hi, @AramMar ! When you see this error (start debugging or profiling)? 
Try to **uninstall/install** extension from vscode. It seems like the extension files have been corrupted.
![image](https://github.com/user-attachments/assets/b2eb678f-60a5-437c-a3e9-854697b78c6f)

**Comment by AramMar** [comment]
Hi @JaneySprings,
for both cases the error happens. I tried unistall/install, unfortunatelly does not help.
Also status 
![image](https://github.com/user-attachments/assets/5b75db2e-31c9-43c1-854b-680beaba86f0)

**Comment by JaneySprings** [comment]
Can you check the `Developer Tools / Console` log?
![image](https://github.com/user-attachments/assets/9171b2b7-21a2-4795-848e-bf043f524797)
![image](https://github.com/user-attachments/assets/1fe76468-7209-4a57-ba2f-0435f850c124)
