### ISSUE TITLE
Add setVariable Debugger Support

### ISSUE THREAD

**Issue by mlancione** [JaneySprings/DotNet.Meteor#139]
Currently when trying to set a variable in the Locals section when debugging the error message "setVariable not supported" is displayed.

Test environment: iOS Simulator on MacOS

**Comment by JaneySprings** [comment]
I think that I can do this in the future updates.

For now, you can set a variable in the debug console, for example:
![image](https://github.com/user-attachments/assets/cba14c52-d013-4e78-9af6-27697a0e7e8f)

**Comment by mlancione** [comment]
Thanks for considering adding this feature. It would also be nice to add it to the Watch list context menu like the MAUI extension (see below).

I'm not sure if it's also possible to add it in the main code body when right-clicking a variable. VSCode doesn't seem to allow editing via a tooltip like in Visual Studio.

<img width="294" alt="image" src="https://github.com/user-attachments/assets/11e7a5f4-b4d5-44a7-b07c-05049d5036d7">

**Comment by JaneySprings** [comment]
> nice to add it to the Watch list context menu

Yeah, I think it also will be work. 
I will try to create this feature this weekend.

**Comment by JaneySprings** [comment]
Implemented in `6.0.2`. Check for extension updates in VSCode.
Now you can set a value of any variable:

https://github.com/user-attachments/assets/d278014a-e0d5-456e-8f6a-80a3002071d7

**Comment by mlancione** [comment]
This feature is working great. Thanks for the quick work!
