### ISSUE TITLE
Add Support To Relaunch App/Debugger Without Rebuilding App

### ISSUE THREAD

**Issue by mlancione** [JaneySprings/DotNet.Meteor#140]
Would it be possible to add the ability to relaunch the app and debugger without triggering a rebuild of the app?

**Comment by JaneySprings** [comment]
See (4): https://github.com/JaneySprings/DotNet.Meteor/wiki/Predefined-task-customization#customize-prelaunchtask
Remove `preLaunchTask` from the launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Meteor Debugger",
            "type": "dotnet-meteor.debugger",
            "request": "launch"
        }
    ]
}
```
