### ISSUE TITLE
How to specify the build project

### ISSUE THREAD

**Issue by Jerome2606** [JaneySprings/DotNet.Meteor#141]
I'm new on VS code and I have trouble to launch my MAUI project with VS Code and .NET Meteor.

I have a big folder containing legacy folder Xamarin project and a folder containing the new Maui project.

How can I specify to .Net Meteor extension to use the target project while run & debug ?

Can it be specified in the launch.json file ?

PS: I'm using VS on Windows and I have created a new solution file (.sln) for MAUI but VS Code does not care about sln and which project should be loaded or not ...

**Comment by JaneySprings** [comment]
Hi, @Jerome2606 !
Do you see the following statusbar items in the bottom panel of VSCode? If your opened folder contains multiple project, you can select it here:
![image](https://github.com/user-attachments/assets/31548897-c991-4cc9-ba8e-e0cbe759e572)
