### ISSUE TITLE
Cannot connect to iPad for "Pair to Mac"

### ISSUE THREAD

**Issue by richardst89** [JaneySprings/DotNet.Meteor#142]
I've followed [this guide](https://github.com/JaneySprings/DotNet.Meteor/wiki/Build-and-debug-iOS-application-on-Windows-with-Pair-to-Mac#apple-devices-app), but have had issues trying to connect to my iPad to facilitate testing.

Is this a known limitation?
If so, what devices are supported?

**Comment by JaneySprings** [comment]
Hi, @richardst89! I don't have any iPad device for testing. I will try to reproduce it tomorrow, maybe it is a bug.

**Comment by JaneySprings** [comment]
I cann't reproduce it:
![image](https://github.com/user-attachments/assets/265cd5d2-da66-40a8-a459-aaf3f942215a)

Do you see your device in the `Apple Devices` app?

**Comment by richardst89** [comment]
I think I've misunderstood the setup. For this to work, you need two devices.
1) A mac to do the building
2) An iPad / iPhone to do the presenting.

I was (wrongly) under the assumption you could do (1) with an iPad!

Thanks for testing!
