### ISSUE TITLE
Extension doesn't read RuntimeIdentifier from csproj 

### ISSUE THREAD

**Issue by hrytsenko-clgx** [JaneySprings/DotNet.Meteor#147]
After migrating project to .NET 9 I have started experience issue with build commmand:

`  Executing task: dotnet build -p:Configuration=Debug -p:TargetFramework=net9.0-ios -p:RuntimeIdentifier=iossimulator-arm64 -p:MtouchDebug=true `

RuntimeIdentifier always equals to "iossimulator-arm64", but csproj has value "iossimulator-x64"

Extension should select value from csproj. Because some libraries doesn't support arm64 architecture and it causes build issue ( and we should use x64 architecture instead):

`: error : 
      clang++ exited with code 1:
      ld: building for 'iOS-simulator', but linking in object file (net9.0-ios/iossimulator-arm64/linker-cache/AppCenter.a[arm64][2](MSACAppCenter.o)) bui
      lt for 'iOS'
      clang++: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by JaneySprings** [comment]
You can use the following workaround for `clang++` issues:
https://github.com/JaneySprings/DotNet.Meteor/wiki/How-to-fix-the-error:-clang-exited-with-code-1
