### ISSUE TITLE
Do Xamarin.ios support?

### ISSUE THREAD

**Issue by dingxiaolong** [JaneySprings/DotNet.Meteor#151]
Do this lib only support Dotnet.ios ,MAUI    ,or it also support Xamarin.ios?  
I open a Xamarin.ios  project ,   seems can't run .

**Comment by JaneySprings** [comment]
Hi @dingxiaolong ! This VSCode Extension supports MAUI, Xamarin.iOS and Xamarin.Mac.
What do you mean by `Dotnet.ios`? I created a new dotnet project via `dotnet new ios` and it works:
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/d9c9462d-891c-44b1-8c88-45965ba6f475" />

**Comment by dingxiaolong** [comment]
Hi,  @JaneySprings :  thanks for you feedback .  
I know it support Dotnet.ios  ,    my question is do it suppor Xamarin.ios project ?    
![image](https://github.com/user-attachments/assets/b66d10fe-2ef5-475e-af19-dcac7fee8ab9)

From the description ,   seems it support the Xamarin.ios project ,but I can't run it .
![image](https://github.com/user-attachments/assets/8558a033-8a41-493e-96bb-26a434fad4fb)

You can create a Xamarin.ios project by visual studio. 
![image](https://github.com/user-attachments/assets/829bb61f-022f-46bb-a92c-d05cebc3abf2)

Many thanks.

**Comment by JaneySprings** [comment]
Unfortunately, this extension doesn't support legacy project formats. Only projects starting from net 6.0 and above.
