### ISSUE TITLE
WinUI support

### ISSUE THREAD

**Issue by nikolaykusch** [JaneySprings/DotNet.Meteor#17]
Is there a way to use this for WinUI and run on Windows as desktop app?

**Comment by JaneySprings** [comment]
Hello! Thank you for your question. You probably mean Windows support for MAUI? Now you can debug and run only mobile platforms (Android and iOS). But I think it won't be very difficult to add Mac and Windows support. I mark this as 'enchancement' and try to add this feature in future updates.

**Comment by nikolaykusch** [comment]
Thanks, I'll wait

**Comment by JaneySprings** [comment]
Now you can try 1.50 version with Desktop support. Just select Windows device (or Mac on MacOS) and run the application. 
Debugging on windows is not supported yet. You can launch app without debug (ctrl + F5). If you find a bugs please write an issues. Thanks!
<img width="1440" alt="Screenshot 2022-12-20 at 01 08 55" src="https://user-images.githubusercontent.com/48021947/208527212-aa1e5836-e9ee-4325-81a5-c709df42aeff.png">
