### ISSUE TITLE
XAML IntelliSense support

### ISSUE THREAD

**Issue by melakhvision** [JaneySprings/DotNet.Meteor#24]
When will we get XAML IntelliSense ?
Any estimation of hot reload ?
Please we really need this so much .

**Comment by JaneySprings** [comment]
Hello. I understand that these are very necessary features but I am creating an extension one. HotReload and XAML IntelliSense very complex features and there is no documentation on how it works. I do this in my free time, but I can't say when it will be ready.

**Comment by melakhvision** [comment]
Thank you. Hope to get it soon

**Comment by saint4eva** [comment]
xaml always adds complexity

**Comment by JaneySprings** [comment]
Results for the current version (`2.10-preview3`)

**For classes:**
<img width="907" alt="Screenshot 2023-02-19 at 00 06 24" src="https://user-images.githubusercontent.com/48021947/219890768-f96bd227-7697-41d9-870b-8951f6fc28df.png">

**For properties and events:**
<img width="1002" alt="Screenshot 2023-02-19 at 00 07 04" src="https://user-images.githubusercontent.com/48021947/219890787-be14c311-59ce-49c1-84a2-7b1e1e989d65.png">

**For enums and structures:**
<img width="816" alt="Screenshot 2023-02-19 at 00 08 01" src="https://user-images.githubusercontent.com/48021947/219890796-c8566e78-fdb8-48d5-a9a5-24368f5fd49e.png">

Also supported the third-party controls like the CommunityToolkit

**Comment by melakhvision** [comment]
This is looking awsome <3 !!!!

**Comment by scriptBoris** [comment]
AWESOME! Грац!
