### ISSUE TITLE
Debug.WriteLine not displaying ??

### ISSUE THREAD

**Issue by kjpou1** [JaneySprings/DotNet.Meteor#39]
Can not figure out where the Debug Diagnostics are printed to.  Console works fine.

Sample repo with steps used to create the project and screen shots.

https://github.com/kjpou1/meteorvsctest.git

Additional information please do not hesitate to ask.  Thanks for the project.

**Comment by JaneySprings** [comment]
Hello! Thank you for your issue. 
Debug.WriteLine writes all messages to a separate stdout. Now this is a Debug.log file (`~/.vscode/extension/nromanov.dotnet-meteor-X.XX.X/extension/bin/logs`). You can find your messages by the following string:
```
13:59:40.6393|Mono: ...
```

I want to add different settings for the Mono in the VSCode, including the debug log redirection to the VSCode console.

**Comment by kjpou1** [comment]
Thanks for the information.
