### ISSUE TITLE
<RuntimeIdentifiers> (plural) not supported in csproj

### ISSUE THREAD

**Issue by krixgris** [JaneySprings/DotNet.Meteor#46]
When building in Visual Studio I use the plural RuntimeIdentifiers to build for both x64 and arm64 for Maccatalyst, but I noticed that just makes .net meteor debugger doesn't seem to interpret that, and instead does nothing.
`<RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>`

When I'm working on my project from my other computers with VS Code I have to swap it out and use `<RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>` and just swap manually between arm64 and x64, which works, but it'd be really great if the plural was possible to use.

**Comment by JaneySprings** [comment]
Hello! Thank you for your issue. Meteor automatically builds an application for the selected device. If you have a Mac with the Apple chip, then it will be `maccatalyst-arm64`.

It may be useful if you can choose a Mac with the architecture you need?

<img width="672" alt="image" src="https://user-images.githubusercontent.com/48021947/222885308-f5963900-15db-4256-ae76-cb0d966c8211.png">

**Comment by krixgris** [comment]
I did notice it working exactly as I want it to when I just use Visual Studio Code, but I guess my actual problem is that Visual Studio for Mac 2022 (which feels very highly beta still hah) requires me to have the <RuntimeIdentifier> set in order for it to build an arm application, otherwise it just defaults to Intel.
So ideally I'd like to be able to set up my csproj file so it works both in my visual studio for mac environment, as well as my visual studio code environment.
My specific case is that I use my M1 mac for most of my development, and then I also use my intel Macbook Pro, and since I don't really have any solid environment variables I can use to determine this, I constantly change my csproj file now depending on which machine I use. Not a big deal, but it'd be "nice to have".

Being able to choose Mac with the architecture would be great though, and it'd be even nicer if that selection then overrides the <RuntimeIdentifier(s)> in csproj.

Let me know if I need to clarify any of the above ramblings and I'd be happy to.

**Comment by JaneySprings** [comment]
Now I have made a fix. There are several `runtimeIdentifiers` in my csproj:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/48021947/222893603-35d38d91-71a6-4ed1-b89a-820142a155dd.png">

If you select (Apple Silicon) in the list of devices, then the arm version will be built, if you select (Intel), then the X64 version.
Or if you have a single `RuntimeIdentifier`, then this version of the application will be assembled, which corresponds to your device in the list of devices.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48021947/222893804-0544e3c1-a148-41d1-af97-19df50c42e34.png">

Will this fix be useful for you?

**Comment by krixgris** [comment]
Oh yeah! That fix would be awesome! That'd solve my issue!

**Comment by JaneySprings** [comment]
You can try new `2.15` version right now!

**Comment by krixgris** [comment]
I just tried this on my Intel Mac right now, and it's not quuiiite working I think.
Right now I have both x64 and mac64 in my <Runtimeidentifiers> and it doesn't seem to execute the right binary (I think?).
It throws this error that it can't find the executable now.. user error?
<img width="250" alt="image" src="https://user-images.githubusercontent.com/83347557/222908090-407baef4-fe4c-49f3-a035-22ab09b3841f.png">
`2023-03-04 15:28:17.1157|Error occurred while processing launch request. The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3863, _LSFunction=_LSOpenStuffCallLocal}|DotNet.Meteor.Debug.Session.Start|Main at offset 150 in file:line:column <filename unknown>:0:0
 => StartSession at offset 123 in file:line:column <filename unknown>:0:0
 => Start at offset 117 in file:line:column <filename unknown>:0:0`

However, it does seem like it's starting the build correctly:
`dotnet build "/Users/MyProject.csproj" -c:Debug -f:net7.0-maccatalyst -t:Build -p:RuntimeIdentifier=maccatalyst-x64 `
That said, the binary it creates doesn't run.
If I switch back to `<RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>` it does build and debug my x64 application correctly (this is from my Intel machine), so it does seem to select the correct one for the .net meteor debugger.

Am I doing something incorrectly?

**Comment by JaneySprings** [comment]
Can you try on a new maui project with the different name? Seems like something cached in MacOS

**Comment by krixgris** [comment]
Just tried it now and I still get the exact same error message.
I did a `dotnet new maui -n "MeteorMaui"` and opened it in vs.code, added my launch.json for .net Meteor, added a single line of `<RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>` and the identical error message pops up.

**Comment by krixgris** [comment]
A thing that's noteworthy.. if I do remove the <runtimeidentifiers> and run it, it will build and start debugging correctly.
Then if I put it back again, it appears to build, and debug, but it's actually not running a new build, but the last successful one.

I.e. if you put back <Runtimeidentifiers>, change the code.. such as just change the default clicked message in the new maui project, you'll notice that the changed code won't be reflected.. so it just looks like it works.

**Comment by JaneySprings** [comment]
Yep, I can reproduce this after killing dotnet process. I will try to research this error...

**Comment by JaneySprings** [comment]
Okay, if you specify a `<RuntimeIdentifiers>` property and try pass a `-p:RuntimeIdentifier=` option, then dotnet will create an incorrect application without building a project (there are no dlls or dylib libraries).

Now you can specify **ONLY** `<RuntimeIdentifier>` property for the single runtime. 

Maybe it's a dotnet MAUI bug. I will write it in the `dotnet/maui` repository and add a link here...

**Comment by krixgris** [comment]
Ahh yeah that sounds like a bug.
Great findings though, thanks for such quick response on this as well! Let's hope there's some attention over at dotnet/maui!

**Comment by JaneySprings** [comment]
https://github.com/xamarin/xamarin-macios/issues/17707
