### ISSUE TITLE
ANDROID_SDK_ROOT enviroment variable is deprecated

### ISSUE THREAD

**Issue by viniciuslln** [JaneySprings/DotNet.Meteor#50]
Hello.
According to https://developer.android.com/studio/command-line/variables ANDROID_SDK_ROOT is deprecated and ANDROID_HOME should be used as they point to the same path.
Or during the build step you cam maybe check for both variables for compatibility cases.

**Comment by JaneySprings** [comment]
Hello, thank you for this! I will add an ANDROID_HOME variable check in the future update.
