### ISSUE TITLE
Can't Detect Physical iPad Device

### ISSUE THREAD

**Issue by Tranquilite0** [JaneySprings/DotNet.Meteor#57]
.NET Meteor doesn't detect my physical iPad. I had a quick look through the code, and I think the problem is in the regex for detecting physical Apple devices, which appears to only match iPhone, and does not match iPad. The code in question:

https://github.com/JaneySprings/DotNet.Meteor/blob/40886bd66c169092fa3c990c18a0b639929dc40f/src/DotNet.Meteor.Shared/Apple/SystemProfiler.cs#LL12C1-L12C115

To detect iPads, I'm pretty sure the only thing that needs to happen is modify the Regex to look for "(iPhone|iPad):". You'll probably also want to create a capture group of that part to populate the device name too since it is currently hard coded to be an iPhone too.

**Comment by JaneySprings** [comment]
Hi, @Tranquilite0! Thank you for your issue. I had fixed this bug in [fc68cb6](https://github.com/JaneySprings/DotNet.Meteor/commit/fc68cb6948819236bfcd88a21011016a5eb46f55). I will publish a release as soon as possible.
