### ISSUE TITLE
Could not find a valid Xcode app bundle

### ISSUE THREAD

**Issue by homerokzam** [JaneySprings/DotNet.Meteor#60]
Congratulations!

I use Mac OSX with dotnet sdk 7 ...

I just installed it:
sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json

I did not install Visual Studio from Mac.

And I have the following error:

error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). [/Users/homerokzam/Projects/DotNet/MyMauiApp/MyMauiApp.csproj::TargetFramework=net7.0-maccatalyst]

Can you solve this problem without installing VS for Mac?

Thanks

**Comment by JaneySprings** [comment]
Hello! That you for your issue. Can you try running Xcode and open settings (command + ,)  -> Locations?
You need to make sure that you have `Command Line Tools` selected:
<img width="861" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/9b9d48fc-b8aa-4ad4-a7c4-dbd80c0d7087">

**Comment by homerokzam** [comment]
Thanks. Command Line Tools was already selected.

<img width="855" alt="Screenshot 2023-05-27 at 10 29 50" src="https://github.com/JaneySprings/DotNet.Meteor/assets/2656746/cec0b0b1-2b16-4405-b994-58e2b3d09873">

**Comment by homerokzam** [comment]
Gosh! That is a very good solution of yours.
Thank you very much.

**Comment by JaneySprings** [comment]
**Happy coding!**

You may find some useful features .NET Meteor in [this post](https://dev.to/nromanov/boost-net-maui-development-productivity-6-powerful-features-of-net-meteor-for-vs-code-in-windows-mac-linux-d0b).
I also have a page in [Patreon](https://www.patreon.com/user?u=90342753) if you want to support the project.
