### ISSUE TITLE
How do pair Mac on Windows?

### ISSUE THREAD

**Issue by scriptBoris** [JaneySprings/DotNet.Meteor#61]
In VisualStudio2022 (windows) exist special button Connect to Mac. But this extensions not have the button?
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/29772096/43f97f97-eafe-4f40-9a36-a0a7f1af9153)
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/29772096/d46029b5-81b6-47c3-ac7d-a7fbe218c9e5)

**Comment by JaneySprings** [comment]
Unfortunately, there are no buttons or/and options similar to the Pair To Mac button that you shown above. I should also say that I do not have plans to add this button in the nearest future. Unless I have more resources to implement such features. 😉

I'd like to also emphasize that the Readme file contains the exhausted list of available options and features. I tend to keep this Readme file up-to-date and you can be sure that **if there is no a certain option/feature, this means that this option is unavailable.**

Regards,
Nikita
