### ISSUE TITLE
Support iOS deploying on Windows

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [JaneySprings/DotNet.Meteor#62]
With the current configurations below, the debugger doesn't get attached - nor does my connected device get the app installed.

**What am I doing wrong?**

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Meteor Debugger",
      "type": "dotnet-meteor.debugger",
      "request": "launch",
      "preLaunchTask": "dotnet-meteor: Build"
    }
  ]
}
```

```
using DotNet.Meteor.HotReload.Plugin;
...
    builder
      .UseMauiApp<App>()
      .EnableHotReload()
```

```
Executing task: dotnet build "c:\Users\xx\Documents\xxx\xx\xx\project.csproj" -c:Debug -f:net7.0-ios -t:Build -p:RuntimeIdentifier=ios-arm64

Build succeeded
Time Elapsed 00:00:01.91
 *  Terminal will be reused by tasks, press any key to close it.
```

![image](https://github.com/JaneySprings/DotNet.Meteor/assets/130459814/aae2ca3a-f5e7-43b4-b5cb-039e6d4347a0)

**Comment by JaneySprings** [comment]
Hello! Thank you for your issue. Can you open a `Debug Console` tab and send an output?
<img width="1113" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/2fb0246a-0a37-4c97-a65d-cf7557da51a8">

**Comment by MLB-BIOMETRIC** [comment]
> Hello! Thank you for your issue. Can you open a `Debug Console` tab and send an output? <img alt="image" width="1113" src="https://user-images.githubusercontent.com/48021947/243317416-2fb0246a-0a37-4c97-a65d-cf7557da51a8.png">

Ah! Sorry for not including the ``Debug Console``.

I am getting this issue:
```
Uploading XXX.app package contents... DONE.
ERROR: could not locate c:\Users\xxx\Documents\xxx\xxx\xxx\bin\Debug\net7.0-ios\ios-arm64\XXX.app/Info.plist in app!
```
My .csproj looks like this ``<IpaMetadata>Platforms\iOS\Info.plist</IpaMetadata>``

**Comment by JaneySprings** [comment]
Are you trying to run iOS on Windows?  This is not possible. Some Microsoft iOS tools on Windows are not working at the moment. In my free time I study `idevicedebug.exe` and `idevicemount.exe`, but I can only to install the app without debugging on an iOS device connected to Windows with PairToMac build.

**Comment by MLB-BIOMETRIC** [comment]
> Are you trying to run iOS on Windows? This is not possible. Some Microsoft iOS tools on Windows are not working at the moment. In my free time I study `idevicedebug.exe` and `idevicemount.exe`, but I can only to install the app without debugging on an iOS device connected to Windows with PairToMac build.

I am trying to deploy the app to my connected iPhone through USB. This works in Visual Studio 2022, just without the debugger attached. It used to work with the debugger attached as well, but I think the latest version broke it.

I am just tired of developing in Visual Studio 2022, and instead want to do it more lightweight with your amazing .NET Meteor work! :) 

I think it would work, if it was just able to find my Info.plist - not sure why it can't find it when its correctly located under ``XXX/Platforms/iOS/Info.plist``

**Comment by JaneySprings** [comment]
If you look at the build result (`bin/Debug/net7.0-ios/ios-arm64/YOUR_APP.app`) then this folder will be almost empty. I do not know why, but at the moment `dotnet` cannot build an iOS app on Windows without PairToMac. In addition, as I understand it, `ideviceinstaller`, which uses .NET Meteor, expects an `.ipa` file, not an `.app`.

If you use Windows, then you should use Visual Studio, since it works better and the Microsoft Team knows how everything works there. I'm studying everything myself and I can't guarantee when I'll be able to do iOS support on Windows

**Comment by MLB-BIOMETRIC** [comment]
@JaneySprings Alright! Thanks for your great work. I hope in the future, that .NET Meteor will be working as good as the Full Visual Studio 2022 installation. :) 

I enjoy VSCode much more than the entire Visual Studio 2022.

**Comment by JaneySprings** [comment]
Hi, @MLB-BIOMETRIC ! Sorry for the late response, I will add this feature in the new `6.0.0` version of .NET Meteor!
At the moment, I have already done Debug and HotReload support.

https://github.com/JaneySprings/DotNet.Meteor/pull/126

**Comment by MLB-BIOMETRIC** [comment]
@JaneySprings That is amazing! Thanks for the update.

**Comment by JaneySprings** [comment]
**Pair to Mac** has been added in the `6.1.0` version. Check for updates in the VSCode extensions tab.

Check the following [instruction](https://github.com/JaneySprings/DotNet.Meteor/wiki/Build-and-debug-iOS-application-on-Windows-with-Pair-to-Mac) to enable pair to mac in your projects. **Please note that only physical devices (not simulators) are currently supported.**

I'd love to hear your feedback!
