### ISSUE TITLE
Possibility of using same root namespace and package name?

### ISSUE THREAD

**Issue by mrsauravsahu** [JaneySprings/DotNet.Meteor#64]
Currently the Package name is `DotNetMeteor.HotReload.Plugin` whereas the namespace is `DotNet.Meteor.HotReload.Plugin`

```diff
diff <(echo DotNetMeteor.HotReload.Plugin) <(echo  DotNet.Meteor.HotReload.Plugin) 
< DotNetMeteor.HotReload.Plugin
---
> DotNet.Meteor.HotReload.Plugin
```

The extra `.` has gotten me a few times.

No functionality is broken, but it's a `gotcha` if I write the package name/namespace by hand.

**Comment by JaneySprings** [comment]
Hello! I'm sorry, package pattern `DotNet.*` was reserved by Microsoft in the NuGet.org 😔

**Comment by mrsauravsahu** [comment]
😿
