### ISSUE TITLE
How to get the current selected configuration?

### ISSUE THREAD

**Issue by Ghostbird** [JaneySprings/DotNet.Meteor#71]
Whenever I build my app using .NET Meteor, I have to first check whether the `-p:Environment` value was changed from the previous run. `dotnet` incremental builds doesn't handle that well, and I'll get stuck with an app that e.g. connects to the wrong server. I've got a script that can check the last build's value in the `obj` folder, however depending on the selected build configuration it should check `obj/Debug` or `obj/Release`.

Is there some way to get the build configuration string currently used by Meteor? I've read [the VSCode documentation on variables](https://code.visualstudio.com/docs/editor/variables-reference) and I've had a quick look at the Meteor code. I tried `${command:dotnet-meteor.selectActiveConfiguration}`, however that isn't practical. It will ask me to set the configuration, instead of returning the current value. Additionally, whenever I do that, it will reset the value of `${input:environment}`, which is used both in the dependency, and the build command, and therefore has to be entered twice.

The latter issue I managed to resolve because I could change the order in which these two were resolved. If I first resolve the command, and then the `input:environment`, I only get asked for it once. The former issue would probably need a change to Meteor to work.

Could you please comment on whether I'm correct about these things, and if so, do you think I should make a PR to add a command that only _gets_ the active configuration?

**Comment by JaneySprings** [comment]
Hi, @Ghostbird ! Unfortunately, .NET Meteor doesn't contain any environmental variables. It has only `Event Handlers` for other extensions: https://github.com/JaneySprings/DotNet.Meteor/blob/main/src/VSCode.Extension/exports.ts  

I think it would be nice to have such a feature if you didn't see it in the UI (like a useless command in the `Command Palette`)

**Comment by Ghostbird** [comment]
Excellent point that it shouldn't be visible in the UI. For now I'm using the command `${command:dotnet-meteor.selectActiveConfiguration}`, which does prompt for the value every time, but will have the current value already highlighted, so I just have to hit <kbd>Enter</kbd> one more time. That works fairly well already.

I'll look into this once I've got a bit of time. Which _might_ be in November.

**Comment by Ghostbird** [comment]
I've found that showing the command in the UI is actually done by adding it to the `contributes` section of the `package.json`. So it seems like it should easy to add a command that doesn't show up in the UI. What I haven't found out yet, is whether doing this using a command is the right approach. Maybe it's possible to set the `Configuration` environment variable in the context of a `dotnet-meteor.task` with target `build`. That would eliminate the need to add `-p:Configuration` to the dotnet command, since it'll automatically pick up the environment variable, and it would probably expose `${env:Configuration}` to dependent processes. That feels like a better approach, but it's require some testing to answer questions such as:

- Can you set the environment variables before `dependsOn` tasks run?
- Do `dependsOn` tasks share environment variables with the main task?

**Comment by JaneySprings** [comment]
I will try to allocate time for this and see what can be done with the VSCode API

**Comment by JaneySprings** [comment]
I did a little research, it seems to me that this task is now impossible. Now there is no way to create custom variables for the extension.

I tried creating a variable in the settings that could be used in `${config:meteor.option}`, but it doesn't work. I can't update the option value if it's not exist in the extension settings.
```ts
vscode.workspace.getConfiguration(res.configId).update("myTestOption", "debug", vscode.ConfigurationTarget.Workspace); 
```

**Comment by Ghostbird** [comment]
Did you look at the environment variable mechanism I suggested? It seems that it would nicely integrate with both VSCode's task mechanism and `dotnet`.

**Comment by JaneySprings** [comment]
I don't know how the environment variable will be defined in the VSCode extension. It should also be available to all processes that VSCode runs. I'm also not sure there won't be problems with other operating systems.

**Comment by Ghostbird** [comment]
This code wasn't checked, so I cannot guarantee correctness, but based on what I know, try this:

Remove https://github.com/JaneySprings/DotNet.Meteor/blob/d933f90de504b666f6716aa0c8861bea72dc7bea/src/VSCode.Extension/tasks/build.ts#L29
Change https://github.com/JaneySprings/DotNet.Meteor/blob/d933f90de504b666f6716aa0c8861bea72dc7bea/src/VSCode.Extension/tasks/build.ts#L54 to read:

```js
new vscode.ShellExecution(builder.build(),{ env: { Configuration: ConfigurationController.target } }),
```

**Comment by Ghostbird** [comment]
Also, I don't think you need to worry about different operating systems here. The functionality is built into VSCode, and VSCode is responsible for correctly passing them to the shell. `dotnet` is responsible for picking them up from the shell. Both do this correctly on all supported OSes.

**Comment by JaneySprings** [comment]
Hi!
I've just implemented this feature, the following commands are currently available:
```
dotnet-meteor.activeProjectPath
dotnet-meteor.activeConfiguration
dotnet-meteor.activeTargetFramework
dotnet-meteor.activeDeviceName
dotnet-meteor.activeDeviceSerial
``` 
You can easily use them in any tasks:
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/724e02dd-3e65-413b-a3d4-26580ec67665)

Please feel free to download an update and let me know how it goes. I apologize for the late - we had a **beta** version release at **DevExpress** and I had really much work. 

Btw, what do you think about our beta? Do you find any features useful for your application? 
https://www.devexpress.com/subscriptions/new-2023-2.xml#maui

**Comment by Ghostbird** [comment]
@JaneySprings Thanks! This works like a charm!

We've used DevExpress to great effect in a previous project of ours. It's less suited to our current application.
