### ISSUE TITLE
Can't select a target device/emulator from the opened panel on Mac M1

### ISSUE THREAD

**Issue by hhyyy9** [JaneySprings/DotNet.Meteor#76]
Is this because M1 chip? it shows 'fetching devices' all the time, but show up nothing.
<img width="1178" alt="iShot_2024-01-28_06 58 47" src="https://github.com/JaneySprings/DotNet.Meteor/assets/841277/dee315b5-c48c-44aa-8a98-e930a8028acb">

**Comment by hhyyy9** [comment]
> Hi! It's strange, because your `MacBook-Pro` is selected in the status bar (which means fetching was successful).
> 
> If you are using Android, something may have happened to `adb` (I noticed a couple of times that `adb daemon` may freeze). Try to execute the command in the terminal: `pkill -f adb`.
> 
> anyway, look at the log (`/Users/YOU/.vscode/extensions/nromanov.dotnet-meteor-4.0.6-darwin-arm64/extension/bin/Workspace/logs`), maybe there is an error there

both iOS and Android simulators can't be fetched, I got this error:

2024-01-28 07:11:24.2185|System.Exception: 
at DeviceProvider.GetDevices at Program.AllDevices at Program.Main
/Users/runner/work/1/s/src/DotNet.Meteor.Workspace/DeviceProvider.cs[20]

**Comment by JaneySprings** [comment]
Can you try to execute it manually with: `/Users/YOU/.vscode/extensions/nromanov.dotnet-meteor-4.0.6-darwin-arm64/extension/bin/Workspace/DotNet.Meteor.Workspace --all-devices` ?

**Comment by hhyyy9** [comment]
I just fixed ! I try to use 'Cmd + Shift + P', then selected '.NET MAUI: Configure Android' and '.NET MAUI: Configure Apple', and reset the Android SDK path, finally restart vscode, it works.

**Comment by JaneySprings** [comment]
I do not recommend using `.NET MAUI` and `.NET Meteor` at the same time. The behavior may be unstable.

**Comment by hhyyy9** [comment]
> I do not recommend using `.NET MAUI` and `.NET Meteor` at the same time. The behavior may be unstable.

Thanks for you recommendation, I found that .NET MAUI is unstable certainly

**Comment by hhyyy9** [comment]
> I do not recommend using `.NET MAUI` and `.NET Meteor` at the same time. The behavior may be unstable.

I got a new issue, can't create new MAUI file using solution explore

**Comment by JaneySprings** [comment]
>  can't create new MAUI file using solution explore

I think you should write an issue to the [C# DevKit extension repository](https://github.com/microsoft/vscode-dotnettools/issues)
