### ISSUE TITLE
Add something like `Visual Studio Installer` experience. 

### ISSUE THREAD

**Issue by JaneySprings** [JaneySprings/DotNet.Meteor#78]
Main idea: automatically detect a missing components for the customer specified platform. Show auto-install suggestions.

**Comment by Ghostbird** [comment]
Which components do you mean? .NET SDK? For all other things, I think you could just run `sudo dotnet workload restore`.

**Comment by JaneySprings** [comment]
Hi, @Ghostbird ! I mean the additional components (like AndroidSDK, OpenJDK, XCode with simulators).
My idea, for example:
You bought a new PC -> You have install only VSCode and .NET Meteor -> You have executed a command in VSCode -> Meteor asks you about your preferred platform and automatically installs all components (dotnet, workloads, etc.)

**Comment by Ghostbird** [comment]
Hmm… I don't know how many of your users would have a use for that. Versus how hard it is to make.

On Debian it's can be done in 5 lines of bash that never change unless the URI format for Microsoft's `dotnet.deb` changes, but on Windows, you might have a lot more URIs that change as you can't load everything through a package manager. And personally I found it a nightmare to set-up on MacOS as a lot of stuff seems impossible to set-up through terminal on mac.

So for me it doesn't really add anything of value. I in fact had installed Debian on a machine last week, and I just pasted those install lines from my project README into bash and everything was set-up.

However, if you know you have a lot of users that are new to MAUI, it might be useful. However, you'll need some way to research those numbers. I suspect that here on Github there'll be a bias towards users like me who don't really need this feature.
