### ISSUE TITLE
Add support for custom project configurations

### ISSUE THREAD

**Issue by AlphaNERD-** [JaneySprings/DotNet.Meteor#81]
Hello,

so as the title says, i would like to suggest to add support for custom configurations listed under <Configurations> in the csproj file. Perhaps we could go further by adding a configuration option for the launch configurations just like with the official .NET MAUI launch configurations.

**Comment by JaneySprings** [comment]
Hi @AlphaNERD- ! Thank you for your issue. You can customize a default build task in the `tasks.json` file. Please, check the following wiki:
https://github.com/JaneySprings/DotNet.Meteor/wiki/Predefined-task-customization

For example:
You can create any custom target in the `csproj` file:
```xml
<Target Name="MyCustomTarget">
	<Message Text="Hello from MyCustomTarget" Importance="high" />
</Target>
```

and create `tasks.json` file in the `.vscode` folder with the following content:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "dotnet-meteor.task",
			"target": "build",
			"problemMatcher": [
				"$dotnet-meteor.problemMatcher"
			],
			"label": "dotnet-meteor: Build",
			"args": [
				"-t:MyCustomTarget"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

You can see that your custom target had executed:
<img width="564" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/a16e344d-47fd-463e-8fa8-a3fe49189baf">
