### ISSUE TITLE
[HotReload][Error]: Permission denied

### ISSUE THREAD

**Issue by terryrau** [JaneySprings/DotNet.Meteor#86]
I get this right after [Mono] Thread started: .NET Sockets #2, I am cannot figure out what permission need to be updated. 

Macos 14.4
net8.0 - maccatalyst

**Comment by JaneySprings** [comment]
Hi, @terryrau! Check the following solution: https://github.com/JaneySprings/DotNet.Meteor/issues/82#issuecomment-1969792995

**Comment by terryrau** [comment]
Thanks that did the trick. Sorry, I didn't see that closed issue.
