### ISSUE TITLE
MongoDB Realm not loading correctly when debugging with NET Meteor - only for Android

### ISSUE THREAD

**Issue by sindrevr** [JaneySprings/DotNet.Meteor#87]
Hi,
There seems to be a bug when trying to debug Android emulator and Physical device when using Realm SDK in the project.
Works fine with IOS/MAC Framework. The problem is when starting the app and initializing and currentuser is always equal null and therefore needs to login everytime after restarting/re-compiling the code.

This does not happen when using .NET Maui extension when debugging in VSCode.
Sample app that does fail with Meteor and succeed with .NET Maui is the classic Realm Todo.
https://github.com/mongodb/template-app-maui-todo

Any tip how to fix this?

**Comment by JaneySprings** [comment]
Hi, @sindrevr ! Can you try to disable this option in the VSCode settings?

https://github.com/JaneySprings/DotNet.Meteor/issues/58#issuecomment-1585600852

**Comment by sindrevr** [comment]
Hi @JaneySprings !
Thank you for your fast reply and great tip.
Now it works as expected 😄
