### ISSUE TITLE
Mono Debugger cannot be attached to WinUI applications?

### ISSUE THREAD

**Issue by ne0rrmatrix** [JaneySprings/DotNet.Meteor#88]
Title says it all. Downloaded extension and tried to run an app in debug mode. Cannot run it on windows. No idea why it is not working. I uninstalled maui extension and installed yours. I am now going to uninstall and go back to I know what works. Your blog post looks great but the very first time I try and run it on a known good repo it just flat out does not work. I don't have time to troubleshoot this. It looked super nice on the blog post. 

I will try it again sometime in the future. I was hoping it would just work. I hope I can get dotnet maui working again in vscode. I wish it was as easy to use as visual studio. 

I will mention it was working when I used the dotnet maui extension. I was told to uninstall Maui extension on reddit. Was this not correct? I don't want conflicting extensions. Do I need to run it side by side with the maui extension?

**Comment by JaneySprings** [comment]
Please, read the readme
https://github.com/JaneySprings/DotNet.Meteor?tab=readme-ov-file#compatibility

WinUI applications don't use [Mono framework](https://www.mono-project.com/). To debug WinUI application you should use a VisualStudio .NET Core debugger, distributed **ONLY WITH**  VisualStudio for Windows or C# VSCode extension.

**Comment by ne0rrmatrix** [comment]
So if I want to run Maui windows apps I have to use an extension other than yours? Any plans to add support for windows in the future? Its great I can run in release mode. I almost never run in release mode.

**Comment by JaneySprings** [comment]
For now, you can run WinUI Applications without debugging, with XAML HotReload and Profiling. 
`VSDBG` says:
```
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
```
I think that i haven't the rights for using VSDBG.

**Comment by JaneySprings** [comment]
> I will be going back to powershell for building.

Why are you using powershell? .NET Meteor can build it and run:
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/6b287881-08f0-43c8-835a-27661d984ac2)
