### ISSUE TITLE
Release also on Open VSX

### ISSUE THREAD

**Issue by Captainpast** [JaneySprings/DotNet.Meteor#91]
I would like to see **.NET Meteor** also released on [Open VSX](https://open-vsx.org), to be available in Eclipse Theia, VSCodium, GitLab IDE, Google IDX and much more

**Comment by Captainpast** [comment]
Thank you very much for publishing on [Open VSX](https://open-vsx.org/).
https://open-vsx.org/extension/nromanov/dotnet-meteor

**Comment by JaneySprings** [comment]
Thank you for your feedback!
