### ISSUE TITLE
Android: Auto rotate always enables on debug start

### ISSUE THREAD

**Issue by Ghostbird** [JaneySprings/DotNet.Meteor#93]
1. Connect Android phone by USB
2. Start a debug session
3. Auto-rotate is enabled on the phone

This also happened previously when using the .NET Comet extension, but I have no idea what exactly causes it. I'm sure it's not something our app does by itself, because it only happens when I debug.

It's not a big issue, but it's a small annoyance very often.

**Comment by JaneySprings** [comment]
Fixed in `4.5.6`

**Comment by Ghostbird** [comment]
Thanks a lot!
