### ISSUE TITLE
Long strings (JSON  or XML) are cut off at the end in the debugger view

### ISSUE THREAD

**Issue by marcoseraphin** [JaneySprings/DotNet.Meteor#94]
I work with different backends which deliveres a JSON (or XML) return value.
But If I hover over the JSON (or XML) var or even put it into the watch window the value is always cut of at the end with "..."

So the complete value could not be investigated and viewed. Even if I copy the value I just get:

"<ROOT><FUNCTIONS><FUNC MOD_ID=\"1\" MOF_I…"
(original string is way longer)

In the full string the value does end with "MOF_ID='12'>"
But I am not able to check that the MOF_ID has a value of 12.

It would be nice and very helpful if the JSON / XML String is NOT cut off at the end.

Here is a original screenshot of the debugger view using VS Code 1.89.1 and .Net Meteor version v4.5.6

![Bildschirmfoto 2024-05-12 um 09 32 57](https://github.com/JaneySprings/DotNet.Meteor/assets/10572315/f9329678-18c8-4dae-b30c-4ec60e6f6a18)

**Comment by JaneySprings** [comment]
Hi @marcoseraphin!
You can try to increase this limit in the settings or disable it:
<img width="585" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/bfcb97be-d306-4884-a0ff-60641bc5cf5f">

**Comment by marcoseraphin** [comment]
Hi Nikita,

thanx, changed the debugger settings, works now, you can close the issue.

Marco

**Comment by JaneySprings** [comment]
No problem, also you can check another debugger options, like `Group Private \ Static Members`, `Step Over Properties And Operators` or `Automatic Sourcelink Download`. Meteor has a lot of options for the debugger customization.
