### ISSUE TITLE
`gcdump` add more info in the log

### ISSUE THREAD

**Issue by Pastajello** [JaneySprings/DotNet.Meteor#95]
Hello,
Im trying to collect gc dump using the extension. I was able to profile the app using the 'trace' profile, but gcdump is causing me problems.

Here is the config:
<img width="447" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/28345098/08f662dd-e82e-4967-9d64-75321e51f69a">
here is the output:
<img width="729" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/28345098/04446f54-b8df-4eff-bdf7-31dc3e455c27">
I've managed to get the dump using manual methods:
![image](https://github.com/JaneySprings/DotNet.Meteor/assets/28345098/e542701a-6151-4abe-b077-deb88c900b55)

**Comment by JaneySprings** [comment]
Hi @Pastajello ! Can you try this solution from the readme: https://github.com/JaneySprings/DotNet.Meteor?tab=readme-ov-file#troubleshooting ?

**Comment by Pastajello** [comment]
Yup, that fixed it!

(could you maybe add a way to add -v flag to the command?) Thanks!

**Comment by JaneySprings** [comment]
Yep, it's a good idea

**Comment by JaneySprings** [comment]
Hi, @Pastajello ! In the new `.NET Meteor 5.1.0` version, I have connect the debug console input with `dotnet-gcdump`. You will be able to use it options:

<img width="1078" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/a5452adc-923b-4f25-99de-0840f1f623f8">
<img width="872" alt="image" src="https://github.com/JaneySprings/DotNet.Meteor/assets/48021947/c6cc0e61-2e75-43ee-b5af-4c10bc4ed99d">


The new version will be available after the merge #107 pull request!
